#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May  1 12:35:14 2020

@author: tushar
"""

'''Doc Test
'''
import doctest

def add(a, b):
    '''
    >>> add(1,2)
    3
    >>> add(2,2)
    4

    Parameters
    ----------
    a : TYPE
        DESCRIPTION.
    b : TYPE
        DESCRIPTION.

    Returns
    -------
    None.

    '''
    return a+b
    
    
def sub(a: int, b: int)->int:
    '''
    

    Parameters
    ----------
    a : int
        DESCRIPTION.
    b : int
        DESCRIPTION.

    Returns
    -------
    int
        DESCRIPTION.
    
    === THE ABOVE CODE WAS AUTO GENERATED BY SPYDER ===
    '''
    
    
    
    

doctest.run_docstring_examples(add, globals(), verbose=True)
doctest.run_docstring_examples(sub, globals(), verbose=True)
# doctest.testmod() -> does not work in Spyder